server:
  port: 1111


  boot:
    admin:
      client:
        url: http://localhost:9090/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
# Database Configuration
spring:
  application:
    name: Citizen-api
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: pkdb
    password: pkdb

# Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.OracleDialect
          globally_quoted_identifiers: true
          
mail:
    host: smtp.gmail.com
    port: 587
    username: pratikrajk111@gmail.com
    password: "dqvo pfoy paqv zpek" # Ensure to enclose the password in quotes if it contains spaces
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true